version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=db
      - DB_DATABASE=mycrm
      - DB_USERNAME=user
      - DB_PASSWORD=secret
    depends_on:
      - db

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mycrm
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpwd
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
